export {default as About} from './About'
export {default as Footer} from './Footer'
export {default as Navbar} from './Navbar'
export {default as Projects} from './Projects'
export {default as Skills} from './Skills'
export {default as Splash} from './Splash'
